### PR TITLE
Add isValidElement method

### LINKED ISSUE #13: isValidElement is a required method of EnzymeAdapter, but was not implemented
Don't know why this error message popped up only now...
According to blame the check has been there for 9 months.

See https://github.com/bbc/enzyme-adapter-inferno/pull/12

### PR DESCRIPTION
**Pull request by IgnusG**
The adapter implementation kinda broke (don't know when or why now) because of a check for `isValidElement` in [enzyme](https://github.com/airbnb/enzyme/blob/6a9492c12dbd73895defbcf67598825b28cbc93e/packages/enzyme/src/EnzymeAdapter.js#L26)

so this is a basic implementation to get rid of errors like this:
```
isValidElement is a required method of EnzymeAdapter, but was not implemented.
```

Other implementations of this method:
- https://github.com/aweary/enzyme-adapter-preact/blob/master/src/PreactAdapter.js#L203
- https://github.com/facebook/react/blob/15a8f031838a553e41c0b66eb1bcf1da8448104d/packages/react/src/ReactElement.js#L371

Resolves #13

### CODE REVIEW

**Comment by IgnusG** [comment]
Tests are failing because of peer dependency issues. Fixed in https://github.com/bbc/enzyme-adapter-inferno/pull/14

**Comment by eddyerburgh** [comment]
Thanks for identifying the issue. Can you update the dependencies in this PR please?

**Comment by eddyerburgh** [comment]
Can you rename the circle directory to .circleci, the issue is we're building this in circle 1 with node 4

**Comment by IgnusG** [comment]
Sure thing, thanks for the info! Didn't know why it was failing

**Comment by eddyerburgh** [comment]
Thanks 👍

**Pull request merged**
